// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDXBfHWn35Zby8YEDOfZTrHLt7XZQKwJWQ',
    appId: '1:227528650925:web:a62fb0a7143d963a33d624',
    messagingSenderId: '227528650925',
    projectId: 'beruwala-pizza',
    authDomain: 'beruwala-pizza.firebaseapp.com',
    storageBucket: 'beruwala-pizza.firebasestorage.app',
    measurementId: 'G-5VDQYTSJ71',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDubjJohe_5YAWx2eWjWw0CPacgcHeugOY',
    appId: '1:227528650925:android:94a9eb4baf1a80df33d624',
    messagingSenderId: '227528650925',
    projectId: 'beruwala-pizza',
    storageBucket: 'beruwala-pizza.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-nu81RwKaXGC4KoWMg_mzwV3aLjPP53k',
    appId: '1:227528650925:ios:9311eb2716d803c833d624',
    messagingSenderId: '227528650925',
    projectId: 'beruwala-pizza',
    storageBucket: 'beruwala-pizza.firebasestorage.app',
    iosBundleId: 'com.beruwala.pizza.beruwalaPizza',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD-nu81RwKaXGC4KoWMg_mzwV3aLjPP53k',
    appId: '1:227528650925:ios:9311eb2716d803c833d624',
    messagingSenderId: '227528650925',
    projectId: 'beruwala-pizza',
    storageBucket: 'beruwala-pizza.firebasestorage.app',
    iosBundleId: 'com.beruwala.pizza.beruwalaPizza',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDXBfHWn35Zby8YEDOfZTrHLt7XZQKwJWQ',
    appId: '1:227528650925:web:d714e4015e56342f33d624',
    messagingSenderId: '227528650925',
    projectId: 'beruwala-pizza',
    authDomain: 'beruwala-pizza.firebaseapp.com',
    storageBucket: 'beruwala-pizza.firebasestorage.app',
    measurementId: 'G-GY785GJFT8',
  );
}
